metadata:
  name: qwen_rapid_aio
  version: 260103-18
  description: Qwen Image/Text-to-Image setup, v18
  created_at: '2026-01-03T22:10:42.608461Z'
  tested: true
  notes: Initial bundle creation
comfyui:
  repo: https://github.com/comfyanonymous/ComfyUI
  commit: f59f71cf34067d46713f6243312f7f0b360d061f
custom_nodes:
- name: ComfyUI-Manager
  git_url: https://github.com/Comfy-Org/ComfyUI-Manager
  commit_sha: fa009e729ee4a09202ebf9c404c47812efcd29c6
  pip_requirements: []
- name: ComfyUI_essentials
  git_url: https://github.com/cubiq/ComfyUI_essentials
  commit_sha: 9d9f4bedfc9f0321c19faf71855e228c93bd0dc9
  pip_requirements: []
models:
  - name: Qwen-Image-Edit-Rapid-AIO-v18
    description: |
      More 2511, a bit less 2509. 
      Different merging method that I think corrects an issue I was having with many input images.
      euler_ancestral/beta recommended
    model_type: checkpoints
    files:
      - name: Qwen-Image-Edit-Rapid-AIO
        url: https://huggingface.co/Phr00t/Qwen-Image-Edit-Rapid-AIO/resolve/main/v18/Qwen-Rapid-AIO-NSFW-v18.safetensors
        filename: Qwen-Rapid-AIO-NSFW-v18.safetensors
        sha256: 0e81c86567a7812cecbfa0be69a652934f431f428e0cdd1ef2f38c6e029b7c5a
        size_bytes: null
requirements_lock_file: requirements.lock
workflow_file: workflow.json
