metadata:
  name: wan_2.2_i2v
  version: 260105-01
  description: WAN 2.2 Image-to-Video setup
  created_at: '2026-01-05T23:05:29.158053Z'
  author: https://civitai.com/models/1981116?modelVersionId=2512098
  tested: false
  notes: Initial bundle creation

comfyui:
  repo: https://github.com/comfyanonymous/ComfyUI
  commit: f59f71cf34067d46713f6243312f7f0b360d061f

custom_nodes:
  - name: ComfyUI-Manager
    git_url: https://github.com/Comfy-Org/ComfyUI-Manager
    commit_sha: 69a6256e54897e35729a8ac5911f7ccad84cc4c0
    pip_requirements: []
  - name: ComfyUI_Swwan
    git_url: https://github.com/aining2022/ComfyUI_Swwan
    commit_sha: 881bc91790da6b907d3d28e5b91b295b9aef06ee
    pip_requirements: []
  - name: ComfyUI_essentials
    git_url: https://github.com/cubiq/ComfyUI_essentials
    commit_sha: 9d9f4bedfc9f0321c19faf71855e228c93bd0dc9
    pip_requirements: []

models:
  - name: DaSiWa WAN 2.2 I2V 14B v8-v1
    description: |
      WAN 2.2 Image-to-Video 14B.
      FP8+ (FP16 base) precision.
      Includes High Noise and Low Noise variants for different use cases.
    model_type: checkpoints
    custom_node_required: null
    subfolder: Wan/22
    files:
      - name: WAN 2.2 High Noise
        url: https://civitai.com/api/download/models/2512098?type=Model&format=SafeTensor&size=full&fp=fp8
        filename: DasiwaWAN22I2V14BV8V1_tastysinHighV81.safetensors
        sha256: 0704EA1F189F03F197DCF5F6642C2F392664DAD0D2203D73DD70E93B92A8E9FF
        size_bytes: null

      - name: WAN 2.2 Low Noise
        url: https://civitai.com/api/download/models/2512333?type=Model&format=SafeTensor&size=full&fp=fp8
        filename: DasiwaWAN22I2V14BV8V1_tastysinLowV81.safetensors
        sha256: 3AD812EE87ECE9E0CE824D3BE5F7895AE94F373D55B132DBACC45B12BFFC3DE1
        size_bytes: null

  - name: Wan 2.1 VAE
    description: |
      WAN 2.1 VAE
    model_type: vae
    custom_node_required: null
    subfolder: Wan
    files:
      - name: WAN 2.1 VAE
        url: https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors
        filename: wan_2.1_vae.safetensors
        sha256: 2fc39d31359a4b0a64f55876d8ff7fa8d780956ae2cb13463b0223e15148976b
        size_bytes: null

  - name: WAN CLIP umt5-xxl_fp8
    description: |
      Text encoder: NSFW WAN CLIP umt5-xxl_fp8
    model_type: clip
    custom_node_required: null
    subfolder: null
    files:
      - name: NSFW WAN CLIP umt5-xxl_fp8
        url: https://huggingface.co/NSFW-API/NSFW-Wan-UMT5-XXL/resolve/main/nsfw_wan_umt5-xxl_fp8_scaled.safetensors
        filename: nsfw_wan_umt5-xxl_fp8_scaled.safetensors
        sha256: a484bb9739a8d4020ca6f072b5b7329cf13e352b06985497c1f7f81ea98a45c5
        size_bytes: null

  - name: Male and his living cocksleeve (WAN 2.2)
    description: |
      Works well with standard settings and standard Wan 2.2 i2v lightning LoRa
      "he fucks her like a cocksleeve"
    model_type: loras
    custom_node_required: null
    subfolder: cocksleeve
    files:
      - name: Cocksleeve High noise
        url: https://civitai.com/api/download/models/2504253?type=Model&format=SafeTensor
        filename: ManAndHisLivingCocksleeve_v1_5750H.safetensors
        sha256: 035AB6CFB3E75069E0E80247498DB32A4D4C62B1262AE353A1857DA889DBAA29
        size_bytes: null

      - name: Cocksleeve Low noise
        url: https://civitai.com/api/download/models/2504253?type=Model&format=SafeTensor
        filename: ManAndHisLivingCocksleeve_v1_5750L.safetensors
        sha256: 39E79DB671ED961522C037F800A252ECF7B3C6CF1419CFCCF4BF407042F9733F
        size_bytes: null

requirements_lock_file: requirements.lock
workflow_file: workflow.json
